In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Data.csv')

In [3]:
df

,Customer ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3.0,4.0,3.0,...,5.0,4.0,3.0,4.0,4.0,5.0,5.0,25,18.0,0
1,5047,Male,disloyal Customer,25,Business travel,Business,235,3.0,2.0,3.0,...,1.0,1.0,5.0,3.0,1.0,4.0,1.0,1,6.0,0
2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2.0,2.0,2.0,...,5.0,4.0,3.0,4.0,4.0,4.0,5.0,0,0.0,1
3,24026,Female,Loyal Customer,25,Business travel,Business,562,2.0,5.0,5.0,...,2.0,2.0,5.0,3.0,1.0,4.0,2.0,11,9.0,0
4,119299,Male,Loyal Customer,61,Business travel,Business,214,3.0,3.0,3.0,...,3.0,3.0,4.0,4.0,3.0,3.0,3.0,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129875,78463,Male,disloyal Customer,34,Business travel,Business,526,3.0,3.0,3.0,...,4.0,3.0,2.0,4.0,4.0,5.0,4.0,0,0.0,0
129876,71167,Male,Loyal Customer,23,Business travel,Business,646,4.0,4.0,4.0,...,4.0,4.0,5.0,5.0,5.0,5.0,4.0,0,0.0,1
129877,37675,Female,Loyal Customer,17,Personal Travel,Eco,828,2.0,5.0,1.0,...,2.0,4.0,3.0,4.0,5.0,4.0,2.0,0,0.0,0
129878,90086,Male,Loyal Customer,14,Business travel,Business,1127,3.0,3.0,3.0,...,4.0,3.0,2.0,5.0,4.0,5.0,4.0,0,0.0,1
129879,34799,Female,Loyal Customer,42,Personal Travel,Eco,264,2.0,5.0,2.0,...,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0,0.0,0

In [4]:
#null values
df.isnull().sum()

Customer ID                            0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                232
Departure/Arrival time convenient     76
Ease of Online booking                57
Gate location                          8
Food and drink                        21
Online boarding                        7
Seat comfort                           1
Inflight entertainment                 4
On-board service                       3
Leg room service                       2
Baggage handling                       2
Checkin service                        3
Inflight service                       1
Cleanliness                            2
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
satisfaction                           0
dtype: int64

In [5]:
#% Null value
df.isnull().sum()*100/len(df)

Customer ID                          0.000000
Gender                               0.000000
Customer Type                        0.000000
Age                                  0.000000
Type of Travel                       0.000000
Class                                0.000000
Flight Distance                      0.000000
Inflight wifi service                0.178626
Departure/Arrival time convenient    0.058516
Ease of Online booking               0.043887
Gate location                        0.006160
Food and drink                       0.016169
Online boarding                      0.005390
Seat comfort                         0.000770
Inflight entertainment               0.003080
On-board service                     0.002310
Leg room service                     0.001540
Baggage handling                     0.001540
Checkin service                      0.002310
Inflight service                     0.000770
Cleanliness                          0.001540
Departure Delay in Minutes           0.000000
Arrival Delay in Minutes             0.302587
satisfaction                         0.000000
dtype: float64